# Generated by Django 5.0.2 on 2024-03-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_activity_image_alter_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='activities',
        ),
        migrations.AddField(
            model_name='package',
            name='activities',
            field=models.ManyToManyField(related_name='packages', to='home.activity'),
        ),
    ]
