# Generated by Django 5.0.2 on 2024-02-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image_remove_destination_image_destination_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
