# Generated by Django 5.0.2 on 2024-03-24 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_package_activities_package_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='package',
            name='activities',
        ),
        migrations.AddField(
            model_name='package',
            name='activities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.activity'),
            preserve_default=False,
        ),
    ]
