# Generated by Django 5.0.4 on 2024-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking_date_booking_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_gateway',
            field=models.BooleanField(default=False),
        ),
    ]
