# Generated by Django 5.0.2 on 2024-02-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('booking_available', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('activities', models.ManyToManyField(related_name='packages', to='home.activity')),
            ],
        ),
    ]
