# Generated by Django 5.0.4 on 2024-05-30 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.AddField(
            model_name='package',
            name='best_season',
            field=models.CharField(default='Spring', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='map_images'),
        ),
        migrations.AddField(
            model_name='package',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='total_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='total_participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='package',
            name='day_descriptions',
            field=models.ManyToManyField(to='home.daydescription'),
        ),
    ]
