# Generated by Django 5.0.4 on 2024-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_daydescription_remove_package_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='safety_tips',
            field=models.TextField(default=''),
        ),
    ]
