# Generated by Django 5.0.4 on 2024-05-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_package_safety_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country_map',
            field=models.ImageField(blank=True, null=True, upload_to='map_images'),
        ),
    ]
